### ISSUE TITLE
Add ability to specify number of clusters

### ISSUE THREAD

**Issue by gkiss** [rmcgibbo/tungsten#12]
I've been thinking a bit about our folding test case:

If we want to get the most out of tungsten (particularly for protein folding problems - where the RMSD spread is very variable), I think it makes sense to either 
a) specify the number of clusters rather than a RMSD cutoff, or
b) come up with an adaptive mechanism that changes the RMSD cutoff in dependance of the structural diversity in the ensemble after a given sampling round.

But I think a) will do and should be fairly straightforward to include.

**Comment by rmcgibbo** [comment]
We could specify the # of clusters, but how is that supposed to work at the beginning, when there isn't very much data?

**Comment by rmcgibbo** [comment]
Another thing would just be to say "the number of clusters is the number of data points times `x`, and use x=0.1, or 0.01 or something"

**Comment by gkiss** [comment]
I agree. Having a factor makes sense (at least initially).
Let's try that and see what the clustering looks like that way.

**Comment by rmcgibbo** [comment]
cc #13
