### ISSUE TITLE
parallel sparse matrix sum

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/tungsten#2]
Currently the reduction is done entirely on the master rank, in O(size) time. It could be done in parallel in O(log(size)) time.

E.g. figure 39-3: http://http.developer.nvidia.com/GPUGems3/gpugems3_ch39.html

**Comment by rmcgibbo** [comment]
I thought about this for a little while, and it made my head hurt.

**Comment by rmcgibbo** [comment]
Perhaps something that @proteneer would find fun :)

**Comment by proteneer** [comment]
row sum of N matrices across N nodes?

**Comment by rmcgibbo** [comment]
Yeah, basically. But they're annoying c structs of variable size, so you can't use [MPI_Reduce](http://www.mcs.anl.gov/research/projects/mpi/www/www3/MPI_Reduce.html)

**Comment by rmcgibbo** [comment]
I tried playing around with the parallel reduction from that link, but I'm not sure how to get it to work cleanly when N is not a power of 2.

**Comment by proteneer** [comment]
are you using GPUs or something? and how big are the matrices? and how much do they vary in size per node?

**Comment by rmcgibbo** [comment]
No. Multiple MPI processes.

**Comment by rmcgibbo** [comment]
The current implementation happens around [here](https://github.com/rmcgibbo/tungsten/blob/master/src/ParallelMSM.cpp#L176), where all of the slave ranks send their data to the master, who sums them.

**Comment by proteneer** [comment]
yeah I don't recommend using the GPU way of trying to do the log(N) reduction on the CPU, sounds terribly inefficient depending on your matrix format.

Why not just get each thread to sum the rows naively? Is it because you are using CSC format as opposed to something like CSC?

**Comment by rmcgibbo** [comment]
No, I don't want to use a GPU at all.

**Comment by rmcgibbo** [comment]
The point is that each of my matrices are on separate computers. And I need to sum these matrices. So I could send them all to master, and sum them there, or instead I could sum them like

```
x[1] = x[0] + x[1]
x[3] = x[2] + x[3]
x[5] = x[4] + x[5]
x[7] = x[6] + x[7]

x[3] = x[1] + x[3]
x[7] = x[5] + x[7]

x[7] = x[3] + x[7]
```

**Comment by rmcgibbo** [comment]
There are no threads.

**Comment by rmcgibbo** [comment]
This is the parallel reduction in MPI, but only when size is a power of 2.
https://gist.github.com/rmcgibbo/7178576

**Comment by proteneer** [comment]
When you say size, you mean the number of matrices and not the size of each matrix right?

**Comment by rmcgibbo** [comment]
Yeah, `size` there is the number of processors (=the number of matrices). For the purpose of this, the sum of one matrix with another matrix is really an "elementary" process, implemented in a single call on a single CPU. So the issue is just about which processors should be sending their data to which other processors in which order.

**Comment by rmcgibbo** [comment]
I think if you compute the last power of 2 less than the # of processors, and call that M, then every processor with rank >= M (e.g. if there are 7 processors, then the ones with index [4, 5, 6]) first starts by sending their data to the "left", (e.g. down in rank) by M, then all of the data will be concentrated within the first M ranks and then you can do the algorithm that only works for powers of two.

**Comment by proteneer** [comment]
OK -  let me explain the power of 2 thing on the GPU. Each GPU warp has at most 32 concurrent threads. In most cases, N >> 32, so the overhead is at 1 warp being the straggler/inefficient one. The last warp that processes the uneven overflow might even just add the stragglers in serial.  

That being said, if N >> number of concurrent nodes you have, you can still do something similar. Observe that you only need to extra careful with the first pass.

Suppose size=11:

```
offset: 2^(floor(log_2(11))) = 8
  rank  0  1  2  3  4  5  6  7  8  9  10 11
target = rank+offset
target  8  9 10 11 12 13 14 15  x  x  x  x  x  

ranks 0-7 are the receivers, 8-15 are senders 
if( is_sender )
    if(rank >= offset): send zero matrix
    else: send rank's matrix
```

So after one round, you end up with a size that is a power of 2. Does this sorta make sense?

**Comment by rmcgibbo** [comment]
I think so. I'll post once I have a solution :)

**Comment by proteneer** [comment]
Sorry I keep forgetting that the number of ranks is not always a power of two on MPI. So you'd probably need to modify the code on the receiving end:

```
offset: 2^(floor(log_2(11))) = 8
  rank  0  1  2  3  4  5  6  7  8  9  10 11
target = rank+offset
target  8  9 10 11 12 13 14 15  x  x  x  x  x  

ranks 0-7 are the receivers, 8-15 are senders 
if( is_receiver )
    if(size >= size % offset): do not expect to receive anything
    else: receiver from sender and reduce
```

**Comment by rmcgibbo** [comment]
Sweet. Its working now.

**Comment by proteneer** [comment]
nice!

**Comment by rmcgibbo** [comment]
One kind of annoying thing is that the result ends up on `rank=(1>>log2(size))-1`, which is really not the most convenient.

**Comment by rmcgibbo** [comment]
It should be possible to have the power-of-two portion send the messages down in index instead of up, and then I think the result would end up on rank 0.

**Comment by rmcgibbo** [comment]
BOOM.

**Comment by proteneer** [comment]
did you blow your house up

**Comment by rmcgibbo** [comment]
```
mpic++ test.c && mpirun -np 21 ./a.out
Final Result on Rank0 =  210
Correct result = 210
```

**Comment by proteneer** [comment]
how much faster is it?

**Comment by rmcgibbo** [comment]
Lolz. It's just adding integers. With each MPI rank being a separate spawned process, I'm sure its much slower.

**Comment by rmcgibbo** [comment]
This is added in b1add76600c4be31d6ead3ae4c03f859bb44d2ff, but I need to add tests before I'm confident enough to enable it. Currently it's not being used.

**Comment by proteneer** [comment]
when testing this type of stuff, good unit tests are of size 0, 1, prime numbers, very large prime numbers, and powers of 2 +- 1
